Repository aregtech/areg-sdk, pull requests merged in 2022-12, with the labels that each got.

#81 Implemented issue #69, isolated and renamed OS specific implementation
  framework/areg/base/IESynchObject.hpp
  framework/areg/base/NEUtilities.hpp
  framework/areg/base/Process.hpp
  framework/areg/base/SynchObjects.hpp
  framework/areg/base/Thread.hpp
  framework/areg/base/private/IESynchObject.cpp
  framework/areg/base/private/NEUtilities.cpp
  framework/areg/base/private/Process.cpp
  framework/areg/base/private/SynchObjects.cpp
  framework/areg/base/private/Thread.cpp
  framework/areg/base/private/posix/NEUtilitiesPosix.cpp
  framework/areg/base/private/posix/ProcessPosix.cpp
  framework/areg/base/private/posix/SynchLockAndWaitIX.cpp
  framework/areg/base/private/posix/SynchLockAndWaitIX.hpp
  framework/areg/base/private/posix/SynchObjectsPosix.cpp
  framework/areg/base/private/posix/ThreadPosix.cpp
  framework/areg/base/private/win32/NEUtilitiesWin32.cpp
  framework/areg/base/private/win32/ProcessWin32.cpp
  framework/areg/base/private/win32/SynchObjectsWin32.cpp
  framework/areg/base/private/win32/ThreadWin32.cpp
  framework/areg/component/TimerBase.hpp
  framework/areg/component/private/TimerBase.cpp
  framework/areg/component/private/TimerManager.cpp
  framework/areg/component/private/TimerManager.hpp
  framework/areg/component/private/WatchdogManager.cpp
  framework/areg/component/private/WatchdogManager.hpp
  framework/areg/component/private/posix/TimerBasePosix.cpp
  framework/areg/component/private/posix/TimerManagerPosix.cpp
  framework/areg/component/private/posix/WatchdogManagerPosix.cpp
  framework/areg/component/private/win32/TimerBaseWin32.cpp
  framework/areg/component/private/win32/TimerManagerWin32.cpp
  framework/areg/component/private/win32/WatchdogManagerWin32.cpp
  framework/mcrouter/app/MulticastRouter.hpp
  framework/mcrouter/app/private/MulticastRouter.cpp
  framework/mcrouter/app/private/posix/MulticastRouterPosix.cpp
  framework/mcrouter/app/private/win32/MulticastRouterWin32.cpp
Labels: improvement, refactoring

#83 Binary suffix 'out' and router & log init copying
  CMakeLists.txt
  conf/cmake/common.cmake
Labels: cmake

#85 Hot fixes of bugs
  conf/cmake/common.cmake
  conf/cmake/user.cmake
  examples/01_hello/src/main.cpp
  examples/02_buffer/src/main.cpp
  examples/03_file/src/main.cpp
  examples/04_trace/src/main.cpp
  examples/05_timer/src/main.cpp
  examples/06_threads/src/main.cpp
  examples/07_synch/src/main.cpp
  examples/08_service/src/ServicingComponent.cpp
  examples/08_service/src/ServicingComponent.hpp
  examples/08_service/src/main.cpp
  examples/09_svcmulti/src/ServicingComponent.cpp
  examples/09_svcmulti/src/ServicingComponent.hpp
  examples/20_pubdatarate/common/NELargeData.hpp
  examples/20_pubdatarate/pubclient/src/ServiceClient.cpp
  examples/20_pubdatarate/pubservice/src/ServicingComponent.cpp
  examples/20_pubdatarate/pubservice/src/ServicingComponent.hpp
  framework/areg/appbase/Application.hpp
  framework/areg/appbase/private/Application.cpp
  framework/areg/base/NECommon.hpp
  framework/areg/base/NEUtilities.hpp
  framework/areg/base/TEString.hpp
  framework/areg/base/private/FileBase.cpp
  framework/areg/base/private/NEUtilities.cpp
  framework/areg/base/private/Process.cpp
  framework/areg/base/private/Socket.cpp
  framework/areg/base/private/String.cpp
  framework/areg/base/private/WideString.cpp
  framework/areg/base/private/posix/SpinLockIX.cpp
  framework/areg/base/private/posix/SpinLockIX.hpp
  framework/areg/component/ProxyEvent.hpp
  framework/areg/component/StubEvent.hpp
  framework/areg/component/private/ClientInfo.cpp
  framework/areg/component/private/ProxyEvent.cpp
  framework/areg/component/private/ServiceManager.cpp
  framework/areg/component/private/ServiceManager.hpp
  framework/areg/component/private/StubEvent.cpp
  framework/areg/ipc/private/ClientReceiveThread.cpp
  framework/areg/ipc/private/ClientReceiveThread.hpp
  framework/areg/ipc/private/ClientSendThread.cpp
  framework/areg/ipc/private/ClientSendThread.hpp
  framework/areg/ipc/private/ClientService.cpp
  framework/areg/ipc/private/ClientService.hpp
  framework/mcrouter/app/private/ConsoleService.cpp
  framework/mcrouter/app/private/ConsoleService.hpp
  framework/mcrouter/tcp/private/ServerReceiveThread.cpp
  framework/mcrouter/tcp/private/ServerReceiveThread.hpp
Labels: bug, C++, improvement

#86 Improvements of examples. Added live duration in Model
  examples/08_service/src/main.cpp
  framework/areg/appbase/Application.hpp
  framework/areg/appbase/private/Application.cpp
  framework/areg/base/NEUtilities.hpp
  framework/areg/component/ComponentLoader.hpp
  framework/areg/component/NERegistry.hpp
  framework/areg/component/private/ComponentLoader.cpp
  framework/areg/component/private/ComponentThread.cpp
  framework/areg/component/private/NERegistry.cpp
Labels: C++, improvement

#91 fixed cmake scripts
  conf/cmake/common.cmake
  conf/cmake/user.cmake
Labels: cmake

#92 Fixed compiler warning
  framework/areg/base/private/posix/ProcessPosix.cpp
Labels: C++, improvement

#98 Feature/60 integrate google test
  .gitmodules
  CMakeLists.txt
  conf/cmake/common.cmake
  conf/cmake/user.cmake
  examples/CMakeLists.txt
  framework/CMakeLists.txt
  tests/CMakeLists.txt
  tests/units/CMakeLists.txt
  tests/units/DemoTest.cpp
Labels: enhancement, cmake, improvement

#99 Example 14 and all model load bug fix
  examples/14_pubtraffic/14_generated.vcxproj
  examples/14_pubtraffic/14_generated.vcxproj.filters
  examples/14_pubtraffic/generated/src/NESimpleTrafficLight.hpp
  examples/14_pubtraffic/generated/src/NESimpleTrafficSwitch.hpp
  examples/14_pubtraffic/generated/src/SimpleTrafficLightClientBase.hpp
  examples/14_pubtraffic/generated/src/SimpleTrafficLightStub.hpp
  examples/14_pubtraffic/generated/src/SimpleTrafficSwitchClientBase.hpp
  examples/14_pubtraffic/generated/src/SimpleTrafficSwitchStub.hpp
  examples/14_pubtraffic/generated/src/private/CMakeLists.txt
  examples/14_pubtraffic/generated/src/private/Makefile
  examples/14_pubtraffic/generated/src/private/NESimpleTrafficLight.cpp
  examples/14_pubtraffic/generated/src/private/NESimpleTrafficSwitch.cpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficLightClientBase.cpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficLightEvents.cpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficLightEvents.hpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficLightProxy.cpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficLightProxy.hpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficLightStub.cpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficSwitchClientBase.cpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficSwitchEvents.cpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficSwitchEvents.hpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficSwitchProxy.cpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficSwitchProxy.hpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficSwitchStub.cpp
  examples/14_pubtraffic/pubclient/src/TrafficLightClient.cpp
  examples/14_pubtraffic/pubclient/src/TrafficLightClient.hpp
  examples/14_pubtraffic/pubclient/src/main.cpp
  examples/14_pubtraffic/pubservice/src/TrafficLightService.cpp
  examples/14_pubtraffic/pubservice/src/TrafficLightService.hpp
  examples/14_pubtraffic/pubservice/src/main.cpp
  examples/14_pubtraffic/res/SimpleTrafficLight.siml
  examples/14_pubtraffic/res/SimpleTrafficSwitch.siml
  examples/14_pubtraffic/res/generate.bat
  examples/14_pubtraffic/res/generate.sh
  framework/areg/appbase/Console.hpp
  framework/areg/component/ProxyBase.hpp
  framework/areg/component/private/ComponentLoader.cpp
  framework/areg/component/private/RemoteEventFactory.cpp
Labels: bug, C++, improvement
