Repository aregtech/areg-sdk, pull requests merged in 2022-02, with the labels that each got.

#41 Integrate CMake file
  CMakeLists.txt
  conf/cmake/common.cmake
  conf/cmake/user.cmake
Labels: enhancement, cmake

#42 cmake minimum version
  CMakeLists.txt
Labels: cmake

#44 Thread/ThreadAddress - Use std::string instead of String
  examples/00_helloservice/generated/src/private/HelloServiceStub.cpp
  examples/01_hello/src/main.cpp
  examples/02_buffer/src/main.cpp
  examples/04_trace/src/main.cpp
  examples/05_timer/src/main.cpp
  examples/06_threads/src/main.cpp
  examples/07_synch/src/main.cpp
  examples/10_locsvc/generated/src/private/HelloWorldStub.cpp
  examples/11_locmesh/generated/src/private/HelloWorldStub.cpp
  examples/11_locmesh/locsvcmesh/src/ServiceClient.cpp
  examples/12_pubsvc/generated/src/private/HelloWorldStub.cpp
  examples/12_pubsvc/pubclient/src/ServiceClient.cpp
  examples/13_pubmesh/generated/src/private/LocalHelloWorldStub.cpp
  examples/13_pubmesh/generated/src/private/LocalServiceClient.cpp
  examples/13_pubmesh/generated/src/private/RemoteRegistryStub.cpp
  examples/13_pubmesh/generated/src/private/RemoteServiceClient.cpp
  examples/13_pubmesh/generated/src/private/SystemShutdownStub.cpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficLightStub.cpp
  examples/14_pubtraffic/generated/src/private/SimpleTrafficSwitchStub.cpp
  examples/15_pubworker/generated/src/private/PatientInformationStub.cpp
  examples/16_pubfsm/generated/src/private/PowerManagerStub.cpp
  examples/16_pubfsm/generated/src/private/TrafficControllerStub.cpp
  examples/17_winchat/generated/private/CentralMessagerStub.cpp
  examples/17_winchat/generated/private/ConnectionManagerStub.cpp
  examples/17_winchat/generated/private/DirectConnectionStub.cpp
  examples/17_winchat/generated/private/DirectMessagerStub.cpp
  framework/areg/base/NESocket.hpp
  framework/areg/base/String.hpp
  framework/areg/base/Thread.hpp
  framework/areg/base/ThreadAddress.hpp
  framework/areg/base/ThreadLocalStorage.hpp
  framework/areg/base/private/NESocket.cpp
  framework/areg/base/private/Thread.cpp
  framework/areg/base/private/ThreadAddress.cpp
  framework/areg/base/private/ThreadLocalStorage.cpp
  framework/areg/base/private/posix/ThreadPosix.cpp
  framework/areg/base/private/win32/ThreadWin32.cpp
  framework/areg/component/private/ComponentAddress.cpp
  framework/areg/component/private/ComponentThread.cpp
  framework/areg/component/private/DispatcherThread.cpp
  framework/areg/component/private/ProxyBase.cpp
  framework/areg/component/private/StubBase.cpp
  framework/areg/component/private/TimerManager.cpp
  framework/areg/ipc/private/ClientReceiveThread.cpp
  framework/areg/ipc/private/ClientSendThread.cpp
  framework/mcrouter/tcp/private/ServerReceiveThread.cpp
Labels: c++17 migration

#45 std::string for RuntimeClassID & Process
  framework/areg/appbase/private/Application.cpp
  framework/areg/base/File.hpp
  framework/areg/base/Process.hpp
  framework/areg/base/RuntimeClassID.hpp
  framework/areg/base/Socket.hpp
  framework/areg/base/private/File.cpp
  framework/areg/base/private/Process.cpp
  framework/areg/base/private/posix/FilePosix.cpp
  framework/areg/base/private/posix/ProcessPosix.cpp
  framework/areg/base/private/win32/ProcessWin32.cpp
  framework/areg/trace/private/FileLogger.cpp
Labels: c++17 migration

#46 failed to initialize with substr
  framework/areg/base/Process.hpp
  framework/areg/base/private/Process.cpp
  framework/areg/base/private/RuntimeClassID.cpp
Labels: bug, c++17 migration
