Repository aregtech/areg-sdk, pull requests merged in 2024-12, with the labels that each got.

#459 457 cmake script optimization
  conf/cmake/common.cmake
  conf/cmake/functions.cmake
  conf/cmake/user.cmake
  docs/wiki/02b-cmake-functions.md
  framework/areglogger/CMakeLists.txt
  thirdparty/sqlite3/CMakeLists.txt
Labels: cmake, optimization, bugfix

#462 Toolchain file descriptions
  README.md
  conf/cmake/user.cmake
  conf/exports/config.cmake.in
  conf/exports/example/toolchains/clang-linux-arm32.cmake
  conf/exports/example/toolchains/clang-linux-arm64.cmake
  conf/exports/example/toolchains/clang-linux-x64.cmake
  conf/exports/example/toolchains/clang-linux-x86.cmake
  conf/exports/example/toolchains/clang-win-x64.cmake
  conf/exports/example/toolchains/clang-win-x86.cmake
  conf/exports/example/toolchains/gnu-linux-arm32.cmake
  conf/exports/example/toolchains/gnu-linux-arm64.cmake
  conf/exports/example/toolchains/gnu-linux-x64.cmake
  conf/exports/example/toolchains/gnu-linux-x86.cmake
  conf/exports/example/toolchains/msvc-win-x64.cmake
  conf/exports/example/toolchains/msvc-win-x86.cmake
  docs/wiki/01b-cmake-build.md
  docs/wiki/02a-cmake-config.md
  docs/wiki/02b-cmake-functions.md
  docs/wiki/02c-cmake-integrate.md
  docs/wiki/07c-troubleshooting-integration.md
Labels: documentation

#469 463 cannot start mcrouter service
  framework/areg/base/TEArrayList.hpp
  framework/aregextend/console/OptionParser.hpp
  framework/aregextend/console/private/OptionParser.cpp
  framework/aregextend/service/NESystemService.hpp
  framework/aregextend/service/ServiceApplicationBase.hpp
  framework/aregextend/service/SystemServiceBase.hpp
  framework/aregextend/service/private/ServiceApplicationBase.cpp
  framework/aregextend/service/private/SystemServiceBase.cpp
  framework/aregextend/service/private/posix/ServiceApplicationBasePosix.cpp
  framework/aregextend/service/private/win32/ServiceApplicationBaseWin32.cpp
  framework/logcollector/app/LogCollector.hpp
  framework/logcollector/app/private/LogCollector.cpp
  framework/logcollector/app/private/posix/LogCollectorPosix.cpp
  framework/logcollector/app/private/win32/LogCollectorWin32.cpp
  framework/mcrouter/app/MulticastRouter.hpp
  framework/mcrouter/app/private/MulticastRouter.cpp
  framework/mcrouter/app/private/posix/MulticastRouterPosix.cpp
  framework/mcrouter/app/private/win32/MulticastRouterWin32.cpp
Labels: bug, enhancement, C++, bugfix

#470 Add new DateTimeTest testcase
  tests/units/DateTimeTest.cpp
Labels: unit test

#471 Sorting of containers.
  CMakeLists.txt
  conf/cmake/setup.cmake
  examples/CMakeLists.txt
  framework/areg/base/TEArrayList.hpp
  framework/areg/base/TEFixedArray.hpp
  framework/areg/base/TEHashMap.hpp
  framework/areg/base/TELinkedList.hpp
  framework/areg/base/TEMap.hpp
  framework/areg/base/TESortedLinkedList.hpp
  framework/areg/base/TEStack.hpp
  framework/aregextend/console/private/OptionParser.cpp
  tests/CMakeLists.txt
  tests/units/TEArrayListTest.cpp
  tests/units/TEFixedArrayTest.cpp
  tests/units/TEHashMapTest.cpp
  tests/units/TELinkedListTest.cpp
  tests/units/TEStackTest.cpp
Labels: enhancement, C++, unit test

#472 466 areg build tests
  README.md
  areg-sdk.sln
  docs/wiki/01b-cmake-build.md
  docs/wiki/08a-examples-and-tests.md
  docs/wiki/README.md
  examples/README.md
Labels: documentation

#474 Fixed Readme document.
  README.md
Labels: bug, documentation, bugfix

#475 473 fix readme document
  README.md
Labels: documentation

#477 Fixed issue with ignoring IP-address.
  framework/areg/base/private/NESocket.cpp
Labels: bug, bugfix

#478 336 access mcrouter and logger services from wsl
  framework/areg/base/private/NESocket.cpp
  framework/areg/resources/areg.init
Labels: bug, bugfix
